### ISSUE TITLE
Probabilità&statistiche/capotorti

### ISSUE THREAD

**Issue by DiffUni** [Typing-Monkeys/AppuntiUniversita#1]
Ci sarebbe qualche materiale su probabilità e statistica?

**Comment by DiffUni** [comment]
ma si, giusto per avere una specie di direzione per lo studio che noi stiamo navigando a vista :_), comunque i materiali che avete ci farebbero un sacco comodo. Grazie ancora per tutto sto lavoro, siete i nostri eroi

**Comment by ncvescera** [comment]
Ho appena caricato i materiali che avevamo per questo esame !
Prima di tutto ti consiglio di guardare il file `funzioni.R` dove trovi tutte le funzioni che abbiamo scritto per gli esoneri/esame.
Alcuni file li ho trovati su Unistudium e sono ancora disponibili se ti iscrivi ai vecchi corsi !
Ci sono anche degli esercizi svolti con testo e anche i dati.
Infine, trovi una cartella con un sacco di file messi a caso: esercizi .R, dati, testi di esercizi e altra roba. Potresti trovarci qualcosa di utile, soprattutto nei commenti presenti nei file .R. Se hai voglia e tempo potresti pensare di sistemarli e organizzarli, sarebbe un ottimo contributo a questo progetto !

Spero possano esserti utili !

Spero che questa repo non rimanga a morire e venga utilizzata da tanta altra gente e possa essere di aiuto ad altre povere bestie che dovranno passare quello che abbiamo passato noi 🍌 🐒

**Comment by DiffUni** [comment]
grazie millee <3
