### ISSUE TITLE
Completare Cybersecurity

### ISSUE THREAD

**Issue by ncvescera** [Typing-Monkeys/AppuntiUniversita#11]
Finire di redigere il riassunto di Cybersecurity.

- ### Santini ☑️ 
   - [x] Controllare il pdf contiene tutti gli argomenti delle slide
      - Il pdf risulta incompleto. Mancano la maggior parte degli argomenti. 
   - [x] Ethereum & Smart Contract Security 
   - [x] Race Conditions
   - [x] Fuzz Testing
   - [x] SQL Injection
   - [x] XSS
   - [x] Os Security
   - [x] ID Managing
   - [x] Aggiungere "Pagina dedica"
      - "When in doubt, whip it out. - cirt. Christopher Wistopher" 
  
-  ### Bistarelli ☑️ 
    - [x] CIA (cap1)
    - [x]  Attack Trees (cap1)
    - [x]  Security Principles (cap1)
    - [x]  Authentication paswords (cap3) and kerberos (no libro)
    - [x]  ~~Security Protocols (cap22)~~
    - [x]  Access controls - DAC-RBAC-ABAC (cap4)
    - [x]  Mac (cap2)
    - [x]  Secure interpretation (no libro?)
    - [x]  Trust (cap27)
    - [x]  DB security (cap 5)
    - [x]  Blockchain (No libro)
    - [x] Aggiungere "Pagina dedica"
       - "Oui, con quanto sentimento defeco sul tuo naso, così che ti coli sul mento"

**Comment by F-a-b-r-i-z-i-o** [comment]
Ho alcuni appunti sulla parte del bista, fatti dal libro, precisamente cap1, cap3, cap4, cap27. 
In questi giorni completo il latex e li inserisco, se possono servire...

**Comment by ncvescera** [comment]
Ottimo !

Fanno sempre comodo 🚀 
Noi ci stiamo concentrando sulla parte di Santini, quelli di Bistarelli non li abbiamo ancora guardati.

Gli appunti che hai riguardano tutto il programma del Bista o solo una parte ?

**Comment by F-a-b-r-i-z-i-o** [comment]
Sono solo di una parte, cioè fino a dove avevo seguito :D 

Comunque ce l'ho in .md, li sto portando in latex (presi dal libro) perchè a quanto ricordo lui stesso ci disse di studiare da la. 

In piu' mi informo in questi giorni che altri capitoli del libro devo aggiungere, oppure fatemi sapere voi...

**Comment by ncvescera** [comment]
AHHAHA onestissimo.
Vanno bene cominque !
Se vuoi puoi lasciarli anche in `.md` non è un problema.

Noi siamo ancora su Santini, appena finito quello cerchiamo di capire il programma del Bista (noi non abbiamo seguito nulla 🙃).

Se hai novità aggiornaci pls ❤️ 

Come si chiama il libro che ha consigliato il prof ?

**Comment by F-a-b-r-i-z-i-o** [comment]
Tranquillo, tanto dovevo anche aggiustarli un po', poi se li porto in latex possiamo fare un'unico file. 
Comunque appena ho delle news sul programma completo aggiungo alla lista... 
Ti mando il pdf del libro su telegram

**Comment by ncvescera** [comment]
Perfetto, grazie mille 🌈 

Attendo novità 🦧

**Comment by F-a-b-r-i-z-i-o** [comment]
Gli argomenti fatti sono: 
- CIA (cap1)
-  Attack Trees (cap1)
- Security Principles (cap1)
- Authentication paswords (cap3) and kerberos (no libro) 
- Security Protocols (cap22)
- Access controls - DAC-RBAC-ABAC (cap4)
- Mac (cap2)
- Secure interpretation (?)
- Trust (cap27)
- DB security (cap 5) 
- Blockchain (?)

**Comment by ncvescera** [comment]
Perfetto, grazie mille !

Con `no libro` vuol dire che stanno nelle slide o che devi pensare per capire dove trovare il materiale per studiare ?

**Comment by F-a-b-r-i-z-i-o** [comment]
Che gli argomenti non stanno nel libro, e le slide sono fatte abbastanza male...

**Comment by ncvescera** [comment]
Perfetto, grazie mille !

Già mi immagino come possono essere quelle slide 😨
