### ISSUE TITLE
[Domanda] Si possono pubblicare appunti in pdf?

### ISSUE THREAD

**Issue by michelevantaggi02** [Typing-Monkeys/AppuntiUniversita#54]
**Che domanda hai ?**
Ho notato che ci sono appunti sia scritti in markdown che alcuni in pdf.
Avendo gli appunti scritti in obsidian hanno un formato non interamente compatibile con il markdown di github, posso quindi contribuire pubblicandoli in pdf?

**Comment by CristianCosci** [comment]
Il problema dei file markdown in obsidian deriva soltanto dai link per le interconnessioni tra i vari file o ci sono anche altre problematiche di visualizzazione?
Eventualmente i pdf sono divisi per corsi oppure per argomenti?

**Comment by ncvescera** [comment]
> Avendo gli appunti scritti in obsidian hanno un formato non interamente compatibile con il markdown di github, posso quindi contribuire pubblicandoli in pdf?

Potresti fornirci qualche esempio di com'è scritto un file in Obsidian e quali possibili potroblemi potrebbe causare ?



> Ho notato che ci sono appunti sia scritti in markdown che alcuni in pdf.

Si esatto, stiamo cercando di uniformare tutta la repo e tradurre tutto in LaTex per una migliore portabilità ed usabilità (scrivere in LaTex è molto più semplice e soprattutto è più facile modificarlo)

In generale dipende cosa intendi per "pubblicarli in PDF": se è solo un file pdf e basta sarebbe meglio di no. Avere un file PDF senza un LaTex che è possibile modificare risulterebbe estremamente complesso per chi volesse apportare qualche modifica. Poi certo, se è un file che hai trovato da qualche parte ed è comunque molto valido puoi suggerirlo e provvederemo a tradurlo in LaTex o magari lo traduci direttamente tu.
Se hai solo Markdown puoi proporre quello ed in caso lo porteremo in LaTex (alla fine non esisterà più un file markdown ma solo un PDF e il relativo progetto LaTex).

Il top sarebbe contribuire direttamente con un porgetto LaTex e relativo PDF 🚀

Se vuoi modificare degli appunti che abbiamo già:
- se sono scritti in Markdown modifica direttamente il Markdown oppure traducili in LaTex e modifica quello (cosa molto apprezzata)
- se sono in LaTex modifica il progetto e riaggiorna il PDF

**Comment by michelevantaggi02** [comment]
> Il problema dei file markdown in obsidian deriva soltanto dai link per le interconnessioni tra i vari file o ci sono anche altre problematiche di visualizzazione? 

Ho installato alcuni plugin di visualizzazione che per forza di cose funzionano solo con obsidian o esportandoli in pdf

Ad esempio il codice:
```
\```ad-example

$x^2=2$ soluzione $\alpha > 0$

$\alpha = \sqrt 2$ (soluzione simbolica)

$\alpha$ limite dell'iterazione

$$x_{k+1} = \frac {x^2_k + 2 }{2x_k}$$

\```
```

in obdisian viene mostrato così
![immagine](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/56927140/4b96f7a0-4195-4f03-9de9-670af2001b68)

Mentre in markdown base (visualizzazione da vscode)

![immagine](https://github.com/Typing-Monkeys/AppuntiUniversita/assets/56927140/1e949028-6935-4b08-afc8-dc9ea971a2e5)

inoltre come ben vedete gli snippet in LaTex scritti con i \$ singoli non vengono renderizzati, funzionano solo quelli con il doppio dollaro

> Eventualmente i pdf sono divisi per corsi di insegnamento oppure per argomenti?

Per il momento ho pronto da condividere soltanto calcolo numerico, ho una cartella con diversi file divisi per argomento che poi posso mettere insieme in un unico file, di pdf pronto ho solo il file completo singolo con tutti gli argomenti ma non ci metto niente a esportare tutti i vari argomenti

**Comment by michelevantaggi02** [comment]
> > Avendo gli appunti scritti in obsidian hanno un formato non interamente compatibile con il markdown di github, posso quindi contribuire pubblicandoli in pdf?

Sul commento precedente ho inserito un esempio di codice che non è compatibile, oltre a quello i link si scrivono con la doppia quadra [[link]], che su markdown base non funziona

> > Ho notato che ci sono appunti sia scritti in markdown che alcuni in pdf.
> 
> Si esatto, stiamo cercando di uniformare tutta la repo e tradurre tutto in LaTex per una migliore portabilità ed usabilità (scrivere in LaTex è molto più semplice e soprattutto è più facile modificarlo)

Su obsidian ci sono alcuni plugin per esportare le note in LaTex, ma non avendolo mai usato in pieno non ho mai provato

**Comment by michelevantaggi02** [comment]
> Per caso questo pdf viene generato a partire dal markdown in obsidian?

Esattamente, obsidian offre di default la possibilità di generare un file pdf a partire dal documento in markdown

**Comment by michelevantaggi02** [comment]
> Volendo puoi aprire una pr così possiamo visionare l'eventuale pdf.

Ho aperto una pr #55 con tutto quello che ho al momento, forse la dovevo fare draft

**Comment by CristianCosci** [comment]
> Esattamente, obsidian offre di default la possibilità di generare un file pdf a partire dal documento in markdown

Volendo allora puoi aprire la pr direttamente con il markdown e il pdf allegato in modo da capire la visualizzazione corretta. In questo modo potremmo correggere gli errori di visualizzazione dovuti al formato markdown di obsidian e avere un formato compatibile con github. Solo in seguito potremmo pensare di passare al latex a partire da quel markdown.

Ovviamente se hai tempo e voglia potresti anche aiutarci o farlo direttamente tu questo primo lavoro di "aggiustamento" al markdown "corretto". Poi per convertirlo al latex in un secondo momento possiamo farlo noi e volendo spiegarti come noi gestiamo i latex per questa repo e in generale.

Il tutto naturalmente solo se hai voglia di contribuire e aiutarci a migliorare questa repo. Anche perchè come puoi notare il materiale relativo alla triennale (quello che attualmente può esserti più utile) è molto scarno e non di buonissima qualità. Ed essendo noi ormai prossimi alla laurea non abbiamo particolare modo di ottimizzare quelli della triennale. 
Invece quello relativo alla magistrale è ottimo (:orangutan: approved) e può tranquillamente essere utilizzato per affrontare qualsiasi corso, tant'è che tutti noi abbiamo studiato e preparato ogni esame della magistrale con quei pdf.

**Comment by michelevantaggi02** [comment]
> Ovviamente se hai tempo e voglia potresti anche aiutarci o farlo direttamente tu questo primo lavoro di "aggiustamento" al markdown "corretto". Poi per convertirlo al latex in un secondo momento possiamo farlo noi e volendo spiegarti come noi gestiamo i latex per questa repo e in generale.

Ho dato un'occhiata e sembra che anche github stia provando a creare i loro blocchi evidenziati tipo Admonition, solo che a quanto pare sono ancora molto acerbi in beta [link alla issue](https://github.com/orgs/community/discussions/16925#discussioncomment-6506860).

Per il momento non so che altro si potrebbe fare, ho trovato anche un paio di script che formattano il codice poi in html ma dubito che poi sia portabile in LaTex, quindi eviterei.

**Comment by ncvescera** [comment]
> Su obsidian ci sono alcuni plugin per esportare le note in LaTex, ma non avendolo mai usato in pieno non ho mai provato

@michelevantaggi02 se hai voglia e tempo potresti anche provarlo. Magari oltre a Markdown e PDF puoi aggiungere anche il risultato della conversione automatica in LaTex 🤔 

Per il resto, ho seguito la discussione e sono d'accordo con @CristianCosci. Va benissimo anche caricare Markdonw e PDF così da poterlo aggiustare per avere un rendering decente su GitHub e poi passare in un successivo momento a LaTex.

@CristianCosci possiamo anche convertire automaticamente PDF in LaTex con https://mathpix.com/
Lo stavo provando e sembra funzionare molto bene 🚀

**Comment by michelevantaggi02** [comment]
> > Su obsidian ci sono alcuni plugin per esportare le note in LaTex, ma non avendolo mai usato in pieno non ho mai provato
> 
> @michelevantaggi02 se hai voglia e tempo potresti anche provarlo. Magari oltre a Markdown e PDF puoi aggiungere anche il risultato della conversione automatica in LaTex 🤔 

Posso provare ma non ho mai usato latex per fare documenti interi quindi devo anche scaricarmi i vari tool, appena ho un po' di tempo provo

**Comment by ncvescera** [comment]
> Posso provare ma non ho mai usato latex per fare documenti interi quindi devo anche scaricarmi i vari tool, appena ho un po' di tempo provo

Perfetto 🚀 vedrai sarà molto semplice e ti tornerà utile

**Comment by ncvescera** [comment]
Penso che questa issue può anche essere chiusa 🤔
In caso di altri dubbi la riapriremo
